"use client";
import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api-client";
type Connection = { provider: string; scopes: string[]; expires_at: string };
type Data = { connections: Connection[]; platforms: string[] };
export function ConnectionsPage() {
  const [data, setData] = useState<Data>({ connections: [], platforms: [] }); const [selected, setSelected] = useState(["linkedin"]); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = () => api<Data>("/connections").then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load connections."));
  useEffect(() => { load(); }, []);
  const done = (message: string) => { setError(""); setNotice(message); load(); };
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); selected.forEach((platform) => form.append("platforms", platform)); try { await api("/connections/upload-post", { method: "POST", body: form }); done("Publishing consent was saved."); } catch (cause) { done(cause instanceof Error ? cause.message : "Connection failed."); } }
  return <><h1>Connections &amp; consent</h1><p>Every connection is separate, scoped, expires after 90 days, and can be revoked here.</p>{notice && <p className="notice success" role="status">{notice}</p>}{error && <p className="notice error" role="alert">{error}</p>}<article className="card"><h2>Current connections</h2>{data.connections.length ? <table><thead><tr><th>Provider</th><th>Scopes</th><th>Expires</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{data.connections.map((connection) => <tr key={connection.provider}><td>{connection.provider}</td><td>{connection.scopes.join(", ")}</td><td>{connection.expires_at}</td><td><button className="danger small" onClick={async () => { try { await api(`/connections/${connection.provider}`, { method: "DELETE" }); done(`${connection.provider} disconnected and purged.`); } catch (cause) { done(cause instanceof Error ? cause.message : "Could not disconnect."); } }}>Disconnect &amp; purge</button></td></tr>)}</tbody></table> : <p className="muted">Nothing connected — manual mode is still fully available.</p>}</article><article className="card"><h2>Publishing via Upload-Post</h2><p>Choose exactly which platforms this app may publish to.</p><form onSubmit={connect}><label>Upload-Post API key<input name="api_key" type="password" required /></label><label>Upload-Post username<input name="username" required /></label><fieldset><legend>Allowed platforms</legend>{data.platforms.map((platform) => <label className="check" key={platform}><input type="checkbox" checked={selected.includes(platform)} onChange={() => setSelected(selected.includes(platform) ? selected.filter((item) => item !== platform) : [...selected, platform])} />{platform}</label>)}</fieldset><label className="check"><input name="auto_publish" type="checkbox" />Allow auto-publish as separate consent</label><button>Grant publishing consent</button></form></article><article className="card"><h2>GitHub (read-only)</h2><button className="secondary" onClick={async () => { try { const result = await api<{ authorization_url: string }>("/connections/github/start"); window.location.assign(result.authorization_url); } catch (cause) { done(cause instanceof Error ? cause.message : "GitHub is unavailable."); } }}>Connect GitHub</button></article></>;
}
